# .github/workflows/python-pipeline.yml
name: CI - Projeto NoSQL IoT

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: 📥 Clonar o repositório
      uses: actions/checkout@v4

    - name: 🐍 Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: 📦 Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install pandas pyarrow pytest

    - name: ⚙️ Executar pipeline completo
      run: |
        python airflow/scripts/gerar_dados_json.py
        python src/extracao.py
        python src/transformacao.py
        python src/carga.py

    - name: ✅ Rodar testes com Pytest
      run: |
        PYTHONPATH=. pytest tests/

    - name: 🟢 Finalizado
      run: echo "CI executado com sucesso!"
